version: "3.7"
services:
  app:
    build:
      context: ./  # Your Laravel app's directory
      dockerfile: Dockerfile
    image: request-form
    container_name: sample4
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./storage:/var/www/storage
      - ./bootstrap/cache:/var/www/bootstrap/cache
      - ./:/var/www
    networks:
      - laravel-app
    environment:
      DB_CONNECTION: mysql
      DB_HOST: host.docker.internal  # Replace with your host's IP if necessary
      DB_PORT: 3306
      DB_DATABASE: backend
      DB_USERNAME: smct
      DB_PASSWORD: smct  # Ensure these match your global MySQL setup

  nginx:
    image: nginx:alpine
    container_name: nginx-server
    restart: unless-stopped
    ports:
      - 5005:80  # Map Nginx port (adjust as needed)
    volumes:
      - ./:/var/www  # Mount your app's code into the container
      - ./docker-compose/nginx/default.conf:/etc/nginx/conf.d/default.conf  # Ensure your Nginx config path is correct
    networks:
      - laravel-app

networks:
  laravel-app:
    driver: bridge
