version: "3.7"
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    image: request-form
    container_name: sample4
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./storage:/var/www/storage
      - ./bootstrap/cache:/var/www/bootstrap/cache
      - ./:/var/www
      - mysql_data:/var/lib/mysql
    networks:
      - laravel-app
    environment:
      DB_CONNECTION: mysql
      DB_HOST:  185.199.52.40
      DB_PORT: 3306
      DB_DATABASE: backend
      DB_USERNAME: smct
      DB_PASSWORD: smct  # Ensure this matches your DB password

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql  # MySQL container name or IP address
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: smct
    ports:
      - "8080:80"  # Access phpMyAdmin via localhost:8080
    networks:
      - laravel-app
  
  nginx:
    image: nginx:alpine
    container_name: nginx-server
    restart: unless-stopped
    ports:
      - 5005:5005
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravel-app

networks:
  laravel-app:
    driver: bridge

volumes:
  mysql_data:  # Named volume for MySQL data
