version: "3.7"
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    image: request-form
    container_name: sample4
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./storage:/var/www/storage
      - ./bootstrap/cache:/var/www/bootstrap/cache
      - ./:/var/www
      - mysql_data:/var/lib/mysql
    networks:
      - laravel-app
    environment:
      DB_CONNECTION: mysql
      DB_HOST:  185.199.52.40
      DB_PORT: 3306
      DB_DATABASE: backend
      DB_USERNAME: smct
      DB_PASSWORD: smct  # Ensure this matches your DB password
  mysql:
    image: mysql:8.0
    container_name: mysql-server
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: backend
      MYSQL_USER: smct
      MYSQL_PASSWORD: smct
      MYSQL_ROOT_PASSWORD: smct
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - laravel-app
      
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-server
    restart: unless-stopped
    ports:
      - 5004:80
    environment:
      PMA_HOST: mysql
      PMA_USER: smct
      PMA_PASSWORD: smct
    networks:
      - laravel-app   
    
  nginx:
    image: nginx:alpine
    container_name: nginx-server
    restart: unless-stopped
    ports:
      - 5005:5005
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravel-app

networks:
  laravel-app:
    driver: bridge

volumes:
  mysql_data:  # Named volume for MySQL data
