<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class BranchSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
 
        DB::table('branches')->insert([
            ['branch_code' => 'AKLA', 'branch_name' => 'AKLAN', 'branch' => 'Strong Moto Centrum, Inc.', 'acronym' => 'SMCT', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'ALEN', 'branch_name' => 'ALLEN', 'branch' => 'Strong Moto Centrum, Inc.', 'acronym' => 'SMCT', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'ANTI', 'branch_name' => 'ANTIQUE', 'branch' => 'Strong Moto Centrum, Inc.', 'acronym' => 'SMCT', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'BANTA', 'branch_name' => 'BANTA', 'branch' => 'Strong Moto Centrum, Inc.', 'acronym' => 'SMCT', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'BAYB', 'branch_name' => 'BAYBAY', 'branch' => 'Strong Moto Centrum, Inc.', 'acronym' => 'SMCT', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'BIÑAN', 'branch_name' => 'BIÑAN', 'branch' => 'Strong Moto Centrum, Inc.', 'acronym' => 'SMCT', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'BOHK', 'branch_name' => 'KIA BOHOL', 'branch' => 'Strong Moto Centrum, Inc.', 'acronym' => 'SMCT', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'BOHL', 'branch_name' => 'BOHOL LOGISTIC', 'branch' => 'Strong Moto Centrum, Inc.', 'acronym' => 'SMCT', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'CAGL', 'branch_name' => 'CAGAYAN LOGISTICS', 'branch' => 'Strong Moto Centrum, Inc.', 'acronym' => 'SMCT', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'CALAP', 'branch_name' => 'CALAPE', 'branch' => 'Strong Moto Centrum, Inc.', 'acronym' => 'SMCT', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'CALAP2', 'branch_name' => 'CALAPE 2', 'branch' => 'Strong Moto Centrum, Inc.', 'acronym' => 'SMCT', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'CALI', 'branch_name' => 'CALINAN', 'branch' => 'Strong Moto Centrum, Inc.', 'acronym' => 'SMCT', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'CARMB', 'branch_name' => 'CARMEN BOHOL', 'branch' => 'Strong Moto Centrum, Inc.', 'acronym' => 'SMCT', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'CARMO', 'branch_name' => 'CARMONA', 'branch' => 'Strong Moto Centrum, Inc.', 'acronym' => 'SMCT', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'CARS', 'branch_name' => 'CARCAR', 'branch' => 'Strong Moto Centrum, Inc.', 'acronym' => 'SMCT', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'CATAR', 'branch_name' => 'CATARMAN', 'branch' => 'Strong Moto Centrum, Inc.', 'acronym' => 'SMCT', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'DASMA', 'branch_name' => 'DASMARIÑAS', 'branch' => 'Strong Moto Centrum, Inc.', 'acronym' => 'SMCT', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'DIPL', 'branch_name' => 'DIPOLOG LOGISTICS', 'branch' => 'Strong Moto Centrum, Inc.', 'acronym' => 'SMCT', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'FAMY', 'branch_name' => 'FAMY', 'branch' => 'Strong Moto Centrum, Inc.', 'acronym' => 'SMCT', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'GUIN', 'branch_name' => 'GUINDULMAN', 'branch' => 'Strong Moto Centrum, Inc.', 'acronym' => 'SMCT', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'GUIN2', 'branch_name' => 'GUINDULMAN 2', 'branch' => 'Strong Moto Centrum, Inc.', 'acronym' => 'SMCT', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'JAGN', 'branch_name' => 'JAGNA', 'branch' => 'Strong Moto Centrum, Inc.', 'acronym' => 'SMCT', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'LIPA', 'branch_name' => 'LIPA', 'branch' => 'Strong Moto Centrum, Inc.', 'acronym' => 'SMCT', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'LOAY', 'branch_name' => 'LOAY', 'branch' => 'Strong Moto Centrum, Inc.', 'acronym' => 'SMCT', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'MADRI', 'branch_name' => 'MADRIDEJOS', 'branch' => 'Strong Moto Centrum, Inc.', 'acronym' => 'SMCT', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'MALA', 'branch_name' => 'MALAYBALAY', 'branch' => 'Strong Moto Centrum, Inc.', 'acronym' => 'SMCT', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'MANG', 'branch_name' => 'MANGA', 'branch' => 'Strong Moto Centrum, Inc.', 'acronym' => 'SMCT', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'MANL', 'branch_name' => 'MANDAUE LOGISTICS', 'branch' => 'Strong Moto Centrum, Inc.', 'acronym' => 'SMCT', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'MANP', 'branch_name' => 'MANDAUE SURPLUS', 'branch' => 'Strong Moto Centrum, Inc.', 'acronym' => 'SMCT', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'MOLS', 'branch_name' => 'MOLAVE', 'branch' => 'Strong Moto Centrum, Inc.', 'acronym' => 'SMCT', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'NAIC', 'branch_name' => 'NAIC', 'branch' => 'Strong Moto Centrum, Inc.', 'acronym' => 'SMCT', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'OZAL', 'branch_name' => 'OZAMIZ LOGISTICS', 'branch' => 'Strong Moto Centrum, Inc.', 'acronym' => 'SMCT', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'PAGS', 'branch_name' => 'PAGSANJAN', 'branch' => 'Strong Moto Centrum, Inc.', 'acronym' => 'SMCT', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'SAGBA', 'branch_name' => 'SAGBAYAN', 'branch' => 'Strong Moto Centrum, Inc.', 'acronym' => 'SMCT', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'ILIG', 'branch_name' => 'ILIGAN', 'branch' => 'Des Strong Motors, Inc.', 'acronym' => 'DSM', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'JIMEDSM', 'branch_name' => 'JIMENEZ', 'branch' => 'Des Strong Motors, Inc.', 'acronym' => 'DSM', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'KABA2', 'branch_name' => 'KABASALAN 2', 'branch' => 'Des Strong Motors, Inc.', 'acronym' => 'DSM', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'KATI', 'branch_name' => 'KATIPUNAN', 'branch' => 'Des Strong Motors, Inc.', 'acronym' => 'DSM', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'LABA', 'branch_name' => 'LABASON', 'branch' => 'Des Strong Motors, Inc.', 'acronym' => 'DSM', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'MARA', 'branch_name' => 'MARANDING', 'branch' => 'Des Strong Motors, Inc.', 'acronym' => 'DSM', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'MATI', 'branch_name' => 'MATINA', 'branch' => 'Des Strong Motors, Inc.', 'acronym' => 'DSM', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'RIZA', 'branch_name' => 'RIZAL PAGADIAN', 'branch' => 'Des Strong Motors, Inc.', 'acronym' => 'DSM', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'TACU', 'branch_name' => 'TACURONG', 'branch' => 'Des Strong Motors, Inc.', 'acronym' => 'DSM', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'TORI', 'branch_name' => 'TORIL', 'branch' => 'Des Strong Motors, Inc.', 'acronym' => 'DSM', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'CERI', 'branch_name' => 'CERILLES PAGADIAN', 'branch' => 'Des Strong Motors, Inc.', 'acronym' => 'DSM', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'VILLA', 'branch_name' => 'VILLANUEVA', 'branch' => 'Des Strong Motors, Inc.', 'acronym' => 'DSM', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'CARC', 'branch_name' => 'CARCAR', 'branch' => 'Des Strong Motors, Inc.', 'acronym' => 'DSM', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'CARC2', 'branch_name' => 'CARCAR 2', 'branch' => 'Des Strong Motors, Inc.', 'acronym' => 'DSM', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'CARMC2', 'branch_name' => 'CARMEN 2', 'branch' => 'Des Strong Motors, Inc.', 'acronym' => 'DSM', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'CATM', 'branch_name' => 'CATMON 2', 'branch' => 'Des Strong Motors, Inc.', 'acronym' => 'DSM', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'COMPO', 'branch_name' => 'COMPOSTELA', 'branch' => 'Des Strong Motors, Inc.', 'acronym' => 'DSM', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'DAAN', 'branch_name' => 'DAANBANTAYAN', 'branch' => 'Des Strong Motors, Inc.', 'acronym' => 'DSM', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'DSMA', 'branch_name' => 'CAMBARO', 'branch' => 'Des Strong Motors, Inc.', 'acronym' => 'DSM', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'DSMAO', 'branch_name' => 'ARGAO', 'branch' => 'Des Strong Motors, Inc.', 'acronym' => 'DSM', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'DSMB', 'branch_name' => 'BASAK', 'branch' => 'Des Strong Motors, Inc.', 'acronym' => 'DSM', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'DSMBN', 'branch_name' => 'BALAMBAN', 'branch' => 'Des Strong Motors, Inc.', 'acronym' => 'DSM', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'DSMCN', 'branch_name' => 'CATMON', 'branch' => 'Des Strong Motors, Inc.', 'acronym' => 'DSM', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'DSMDM', 'branch_name' => 'TOLEDO 2', 'branch' => 'Des Strong Motors, Inc.', 'acronym' => 'DSM', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'DSMDN', 'branch_name' => 'CARMEN', 'branch' => 'Des Strong Motors, Inc.', 'acronym' => 'DSM', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'DSMK', 'branch_name' => 'LABANGON', 'branch' => 'Des Strong Motors, Inc.', 'acronym' => 'DSM', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'DSMLN', 'branch_name' => 'LILOAN', 'branch' => 'Des Strong Motors, Inc.', 'acronym' => 'DSM', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'DSMP', 'branch_name' => 'CONSOLACION', 'branch' => 'Des Strong Motors, Inc.', 'acronym' => 'DSM', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'DSMSB', 'branch_name' => 'SUZUKI AUTO BOHOL', 'branch' => 'Des Strong Motors, Inc.', 'acronym' => 'DSM', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'DSMT', 'branch_name' => 'TAGBILARAN', 'branch' => 'Des Strong Motors, Inc.', 'acronym' => 'DSM', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'DSMT2', 'branch_name' => 'TAGBILARAN 2', 'branch' => 'Des Strong Motors, Inc.', 'acronym' => 'DSM', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'DSMTA', 'branch_name' => 'TALAMBAN', 'branch' => 'Des Strong Motors, Inc.', 'acronym' => 'DSM', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'ILOI', 'branch_name' => 'ILOILO', 'branch' => 'Des Strong Motors, Inc.', 'acronym' => 'DSM', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'LAHU', 'branch_name' => 'LAHUG', 'branch' => 'Des Strong Motors, Inc.', 'acronym' => 'DSM', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'LAPU 2', 'branch_name' => 'LAPU-LAPU 2', 'branch' => 'Des Strong Motors, Inc.', 'acronym' => 'DSM', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'DSML', 'branch_name' => 'TOLEDO', 'branch' => 'Des Strong Motors, Inc.', 'acronym' => 'DSM', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'CALIN', 'branch_name' => 'CALINOG Y3S', 'branch' => 'Des Strong Motors, Inc.', 'acronym' => 'DSM', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'ALAD', 'branch_name' => 'ALANO', 'branch' => 'Des Appliance Plaza, Inc.', 'acronym' => 'DAP', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'AURD', 'branch_name' => 'AURORA', 'branch' => 'Des Appliance Plaza, Inc.', 'acronym' => 'DAP', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'BALD', 'branch_name' => 'BALINGASAG', 'branch' => 'Des Appliance Plaza, Inc.', 'acronym' => 'DAP', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'BONI', 'branch_name' => 'BONIFACIO', 'branch' => 'Des Appliance Plaza, Inc.', 'acronym' => 'DAP', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'BUUD', 'branch_name' => 'BUUG', 'branch' => 'Des Appliance Plaza, Inc.', 'acronym' => 'DAP', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'CALD', 'branch_name' => 'CALAMBA', 'branch' => 'Des Appliance Plaza, Inc.', 'acronym' => 'DAP', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'CAMD', 'branch_name' => 'CAMINO NUEVO', 'branch' => 'Des Appliance Plaza, Inc.', 'acronym' => 'DAP', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'DAPI', 'branch_name' => 'DAPITAN', 'branch' => 'Des Appliance Plaza, Inc.', 'acronym' => 'DAP', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'DIPD', 'branch_name' => 'DIPOLOG', 'branch' => 'Des Appliance Plaza, Inc.', 'acronym' => 'DAP', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'DIPD2', 'branch_name' => 'DIPOLOG 2', 'branch' => 'Des Appliance Plaza, Inc.', 'acronym' => 'DAP', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'ILID', 'branch_name' => 'ILIGAN', 'branch' => 'Des Appliance Plaza, Inc.', 'acronym' => 'DAP', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'IMED', 'branch_name' => 'IMELDA', 'branch' => 'Des Appliance Plaza, Inc.', 'acronym' => 'DAP', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'INIT2', 'branch_name' => 'INITAO 2', 'branch' => 'Des Appliance Plaza, Inc.', 'acronym' => 'DAP', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'IPID', 'branch_name' => 'IPIL', 'branch' => 'Des Appliance Plaza, Inc.', 'acronym' => 'DAP', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'JIME', 'branch_name' => 'JIMENEZ', 'branch' => 'Des Appliance Plaza, Inc.', 'acronym' => 'DAP', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'KABD', 'branch_name' => 'KABASALAN', 'branch' => 'Des Appliance Plaza, Inc.', 'acronym' => 'DAP', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'LABD', 'branch_name' => 'LABASON', 'branch' => 'Des Appliance Plaza, Inc.', 'acronym' => 'DAP', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'LILD', 'branch_name' => 'LILOY', 'branch' => 'Des Appliance Plaza, Inc.', 'acronym' => 'DAP', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'MANO', 'branch_name' => 'MANOLO FORTICH', 'branch' => 'Des Appliance Plaza, Inc.', 'acronym' => 'DAP', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'MARA2', 'branch_name' => 'MARAMAG', 'branch' => 'Des Appliance Plaza, Inc.', 'acronym' => 'DAP', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'MARD', 'branch_name' => 'MARANDING', 'branch' => 'Des Appliance Plaza, Inc.', 'acronym' => 'DAP', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'MOLD', 'branch_name' => 'MOLAVE', 'branch' => 'Des Appliance Plaza, Inc.', 'acronym' => 'DAP', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'MOLD2', 'branch_name' => ' MOLAVE 2', 'branch' => 'Des Appliance Plaza, Inc.', 'acronym' => 'DAP', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'NUND2', 'branch_name' => 'NUÑEZ 2', 'branch' => 'Des Appliance Plaza, Inc.', 'acronym' => 'DAP', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'OROD', 'branch_name' => 'OROQUIETA', 'branch' => 'Des Appliance Plaza, Inc.', 'acronym' => 'DAP', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'OZAD', 'branch_name' => 'OZAMIZ', 'branch' => 'Des Appliance Plaza, Inc.', 'acronym' => 'DAP'], 'created_at' => now(), 'updated_at' => now(),
            ['branch_code' => 'PUTD', 'branch_name' => 'PUTIK', 'branch' => 'Des Appliance Plaza, Inc.', 'acronym' => 'DAP','created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'RIZD', 'branch_name' => 'OZAMIZ RIZAL', 'branch' => 'Des Appliance Plaza, Inc.', 'acronym' => 'DAP', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'SANM', 'branch_name' => 'SAN MIGUEL', 'branch' => 'Des Appliance Plaza, Inc.', 'acronym' => 'DAP', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'SIND', 'branch_name' => 'SINDANGAN', 'branch' => 'Des Appliance Plaza, Inc.', 'acronym' => 'DAP', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'SUCD', 'branch_name' => 'SUCABON', 'branch' => 'Des Appliance Plaza, Inc.', 'acronym' => 'DAP', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'TUBOD', 'branch_name' => 'TUBOD', 'branch' => 'Des Appliance Plaza, Inc.', 'acronym' => 'DAP', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'VITA', 'branch_name' => 'VITALI', 'branch' => 'Des Appliance Plaza, Inc.', 'acronym' => 'DAP', 'created_at' => now(), 'updated_at' => now()],
        ]);


    }
}
